version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: invoice-qdrant-prod
    ports:
      - "6333:6333"
    volumes:
      - qdrant_prod_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - invoice-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # FastAPI Backend
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: invoice-backend-prod
    ports:
      - "8000:8000"
    environment:
      # Application settings
      - APP_NAME=Invoice Reimbursement System
      - APP_VERSION=1.0.0
      - DEBUG=false
      - LOG_LEVEL=WARNING
      
      # Security settings - IMPORTANT: Set specific domains in production
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      
      # Qdrant configuration
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY:-}
      
      # API Keys - REQUIRED
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      
      # Vector store configuration
      - COLLECTION_NAME=invoice_reimbursements_prod
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - VECTOR_SIZE=384
      
      # File upload configuration
      - MAX_FILE_SIZE=50
      - ALLOWED_EXTENSIONS=pdf,zip
      - UPLOAD_DIRECTORY=uploads
      
      # LLM configuration
      - LLM_MODEL=gemini-2.5-flash
      - LLM_TEMPERATURE=0.1
      - MAX_TOKENS=4096
      
      # Chat configuration
      - MAX_CONVERSATION_HISTORY=10
    volumes:
      - prod_uploads:/app/uploads
      - prod_logs:/app/logs
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/quick"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - invoice-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Streamlit Frontend
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: invoice-frontend-prod
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_API_BASE_URL=http://backend:8000
      - STREAMLIT_API_TIMEOUT=300
      - STREAMLIT_DEFAULT_CURRENCY=INR
    command: ["python", "-m", "streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]
    volumes:
      - prod_uploads:/app/uploads
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - invoice-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  qdrant_prod_data:
    driver: local
  prod_uploads:
    driver: local
  prod_logs:
    driver: local

networks:
  invoice-network:
    driver: bridge
