version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: invoice-qdrant-dev
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_dev_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - invoice-network

  # FastAPI Backend with Hot Reload
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: invoice-backend-dev
    ports:
      - "8000:8000"
    environment:
      # Application settings
      - APP_NAME=Invoice Reimbursement System
      - APP_VERSION=1.0.0
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      
      # Security settings
      - ALLOWED_HOSTS=*
      
      # Qdrant configuration
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY:-}
      
      # Gemini API configuration
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      
      # Vector store configuration
      - COLLECTION_NAME=invoice_reimbursements_dev
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - VECTOR_SIZE=384
      
      # File upload configuration
      - MAX_FILE_SIZE=50
      - ALLOWED_EXTENSIONS=pdf,zip
      - UPLOAD_DIRECTORY=uploads
      
      # LLM configuration
      - LLM_MODEL=gemini-2.5-flash
      - LLM_TEMPERATURE=0.1
      - MAX_TOKENS=4096
      
      # Chat configuration
      - MAX_CONVERSATION_HISTORY=10
    volumes:
      - .:/app  # Mount entire project for hot reload
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      qdrant:
        condition: service_healthy
    networks:
      - invoice-network
    restart: unless-stopped

  # Streamlit Frontend with Hot Reload
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: invoice-frontend-dev
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_API_BASE_URL=http://backend:8000
      - STREAMLIT_API_TIMEOUT=300
      - STREAMLIT_DEFAULT_CURRENCY=INR
    command: ["python", "-m", "streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true", "--server.runOnSave=true"]
    volumes:
      - .:/app  # Mount entire project for hot reload
      - ./uploads:/app/uploads
    depends_on:
      - backend
    networks:
      - invoice-network
    restart: unless-stopped

volumes:
  qdrant_dev_data:
    driver: local

networks:
  invoice-network:
    driver: bridge
