[theme]
# iAI Solutions inspired theme
# Based on the dark purple/violet color palette from https://www.iaisolution.com/

# Primary colors
primaryColor = "#8B5CF6"          # Purple accent (violet-500)
backgroundColor = "#1E1B2E"       # Dark purple background
secondaryBackgroundColor = "#2D2A3F"  # Slightly lighter purple for cards/containers

# Text colors
textColor = "#FFFFFF"             # White text for high contrast

# Base theme
base = "dark"

# Font configuration
font = "sans serif"               # Clean, modern font

# Additional styling through CSS will be applied via st.markdown
