[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#8B5CF6"
backgroundColor = "#1E1B2E"
secondaryBackgroundColor = "#2D2A3F"
textColor = "#FFFFFF"
font = "sans serif"
